In [1]:
import numpy as np

In [2]:
np.array([[1,2,3],[4,5,6]])

array([[1, 2, 3],
       [4, 5, 6]])

In [3]:
arr=np.array([[1,2,3],[4,5,6]])
arr.ndim#数组的维度的个数
arr.size#总的数的个数
arr.shape#数组的长宽高是多少，形状

(2, 3)

In [4]:
arr=np.array([[1,2,3],[4,5,6]])
print(arr.ndim)#数组的维度的个数
print(arr.size)#总的数的个数
print(arr.shape)#数组的长宽高是多少，形状

2
6
(2, 3)


上面的(2,3)表示是两行三列

In [5]:
lst=[[1,2,3],['1,','5','8']]
arr2=np.array(lst)
print(arr2.ndim)

2


In [7]:
lst=[[1,2,3],['1,','5','8']]
arr2=np.array(lst)
print(arr2)
print(arr2.ndim)
print(arr2.dtype)

[['1' '2' '3']
 ['1,' '5' '8']]
2
<U11


在这里我们可以看到整形被转化成了字符串，所以我们在创建数组的时候尽量保持同一个数据类型，这样就不会遇到互相转换的麻烦了！下面我们把两个一维数组组合成为一个二维数组

In [8]:
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
arrl=np.array([arr1,arr2])
print(arrl)#在进行组合的时候，我们的写法和创建一个一维数组的写法是相同的

[[1 2 3]
 [4 5 6]]


In [9]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [10]:
np.zeros((2,2))#这样子就可以生成一个二维的零向量数组了

array([[0., 0.],
       [0., 0.]])

In [11]:
arra=np.array([list(range(5)),list(range(5))])
print(arra)

[[0 1 2 3 4]
 [0 1 2 3 4]]


In [12]:
arra=np.array([[range(5)],[range(5)]])
print(arra)

[[[0 1 2 3 4]]

 [[0 1 2 3 4]]]


In [13]:
range(5)

range(0, 5)

In [14]:
list(range(5))

[0, 1, 2, 3, 4]

In [15]:
arra=np.array([list(range(5)),list(range(5))])
print(arra)

[[0 1 2 3 4]
 [0 1 2 3 4]]


In [16]:
np.zeros_like(arra)#在保持数组维度不变的情况下，将所有的元素值变为零

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [17]:
np.ones_like(arra)#这个的用法和zeros的用法是完全相同的

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

下面演示创建单位矩阵

In [18]:
np.eye(5)#创建了一个拥有五行五列的单位矩阵

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])